<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Example {

  static $swaggerTypes = array(    
    'id' => 'int',
    'text' => 'string',
    'title' => 'string',
    'exampleId' => 'int',
    'score' => 'ScoredWord',
    'sentence' => 'Sentence',
    'year' => 'int',
    'provider' => 'ContentProvider',
    'word' => 'string',
    'rating' => 'float',
    'url' => 'string',
    'documentId' => 'int'   
    );


    /**
     * 
     */
	 public $id;// int


    /**
     * 
     */
	 public $text;// string


    /**
     * 
     */
	 public $title;// string


    /**
     * 
     */
	 public $exampleId;// int


    /**
     * 
     */
	 public $score;// ScoredWord


    /**
     * 
     */
	 public $sentence;// Sentence


    /**
     * 
     */
	 public $year;// int


    /**
     * 
     */
	 public $provider;// ContentProvider


    /**
     * 
     */
	 public $word;// string


    /**
     * 
     */
	 public $rating;// float


    /**
     * 
     */
	 public $url;// string


    /**
     * 
     */
	 public $documentId;// int


}

?>