<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 */
abstract class IncludePartOfSpeechValues {
  
    public static $Noun = "noun";
    public static $Adjective = "adjective";
    public static $Verb = "verb";
    public static $Adverb = "adverb";
    public static $Interjection = "interjection";
    public static $Pronoun = "pronoun";
    public static $Preposition = "preposition";
    public static $Abbreviation = "abbreviation";
    public static $Affix = "affix";
    public static $Article = "article";
    public static $Auxiliary_verb = "auxiliary-verb";
    public static $Conjunction = "conjunction";
    public static $Definite_article = "definite-article";
    public static $Family_name = "family-name";
    public static $Given_name = "given-name";
    public static $Idiom = "idiom";
    public static $Imperative = "imperative";
    public static $Noun_plural = "noun-plural";
    public static $Noun_posessive = "noun-posessive";
    public static $Past_participle = "past-participle";
    public static $Phrasal_prefix = "phrasal-prefix";
    public static $Proper_noun = "proper-noun";
    public static $Proper_noun_plural = "proper-noun-plural";
    public static $Proper_noun_posessive = "proper-noun-posessive";
    public static $Suffix = "suffix";
    public static $Verb_intransitive = "verb-intransitive";
    public static $Verb_transitive = "verb-transitive";

};
?>