<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class TestData {

  static $swaggerTypes = array(    
    'apiTokenStatusList' => 'Array<ApiTokenStatus>',
    'userList' => 'Array<User>',
    'authenticationTokenList' => 'Array<AuthenticationToken>',
    'wordListList' => 'Array<WordList>',
    'stringList' => 'Array<String>',
    'syllableList' => 'Array<Syllable>',
    'audioTypeList' => 'Array<AudioType>',
    'facetList' => 'Array<Facet>',
    'noteList' => 'Array<Note>',
    'facetValueList' => 'Array<FacetValue>',
    'wordObjectList' => 'Array<WordObject>',
    'relatedList' => 'Array<Related>',
    'scoredWordList' => 'Array<ScoredWord>',
    'citationList' => 'Array<Citation>',
    'exampleSearchResultsList' => 'Array<ExampleSearchResults>',
    'exampleList' => 'Array<Example>',
    'sentenceList' => 'Array<Sentence>',
    'audioFileList' => 'Array<AudioFile>',
    'contentProviderList' => 'Array<ContentProvider>',
    'bigramList' => 'Array<Bigram>',
    'labelList' => 'Array<Label>',
    'frequencyList' => 'Array<Frequency>',
    'partOfSpeechList' => 'Array<PartOfSpeech>',
    'definitionList' => 'Array<Definition>',
    'textPronList' => 'Array<TextPron>',
    'frequencySummaryList' => 'Array<FrequencySummary>',
    'wordListWordList' => 'Array<WordListWord>',
    'stringValueList' => 'Array<StringValue>',
    'wordSearchResultsList' => 'Array<WordSearchResults>',
    'wordSearchResultList' => 'Array<WordSearchResult>',
    'wordFrequencyList' => 'Array<WordFrequency>',
    'wordOfTheDayList' => 'Array<WordOfTheDay>'   
    );


    /**
     * 
     */
	 public $apiTokenStatusList;// Array<ApiTokenStatus>


    /**
     * 
     */
	 public $userList;// Array<User>


    /**
     * 
     */
	 public $authenticationTokenList;// Array<AuthenticationToken>


    /**
     * 
     */
	 public $wordListList;// Array<WordList>


    /**
     * 
     */
	 public $stringList;// Array<String>


    /**
     * 
     */
	 public $syllableList;// Array<Syllable>


    /**
     * 
     */
	 public $audioTypeList;// Array<AudioType>


    /**
     * 
     */
	 public $facetList;// Array<Facet>


    /**
     * 
     */
	 public $noteList;// Array<Note>


    /**
     * 
     */
	 public $facetValueList;// Array<FacetValue>


    /**
     * 
     */
	 public $wordObjectList;// Array<WordObject>


    /**
     * 
     */
	 public $relatedList;// Array<Related>


    /**
     * 
     */
	 public $scoredWordList;// Array<ScoredWord>


    /**
     * 
     */
	 public $citationList;// Array<Citation>


    /**
     * 
     */
	 public $exampleSearchResultsList;// Array<ExampleSearchResults>


    /**
     * 
     */
	 public $exampleList;// Array<Example>


    /**
     * 
     */
	 public $sentenceList;// Array<Sentence>


    /**
     * 
     */
	 public $audioFileList;// Array<AudioFile>


    /**
     * 
     */
	 public $contentProviderList;// Array<ContentProvider>


    /**
     * 
     */
	 public $bigramList;// Array<Bigram>


    /**
     * 
     */
	 public $labelList;// Array<Label>


    /**
     * 
     */
	 public $frequencyList;// Array<Frequency>


    /**
     * 
     */
	 public $partOfSpeechList;// Array<PartOfSpeech>


    /**
     * 
     */
	 public $definitionList;// Array<Definition>


    /**
     * 
     */
	 public $textPronList;// Array<TextPron>


    /**
     * 
     */
	 public $frequencySummaryList;// Array<FrequencySummary>


    /**
     * 
     */
	 public $wordListWordList;// Array<WordListWord>


    /**
     * 
     */
	 public $stringValueList;// Array<StringValue>


    /**
     * 
     */
	 public $wordSearchResultsList;// Array<WordSearchResults>


    /**
     * 
     */
	 public $wordSearchResultList;// Array<WordSearchResult>


    /**
     * 
     */
	 public $wordFrequencyList;// Array<WordFrequency>


    /**
     * 
     */
	 public $wordOfTheDayList;// Array<WordOfTheDay>


}

?>