<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 */
abstract class TypeValues {
  
    public static $Synonym = "synonym";
    public static $Antonym = "antonym";
    public static $Variant = "variant";
    public static $Equivalent = "equivalent";
    public static $Cross_reference = "cross-reference";
    public static $Related_word = "related-word";
    public static $Rhyme = "rhyme";
    public static $Form = "form";
    public static $Etymologically_related_term = "etymologically-related-term";
    public static $Hypernym = "hypernym";
    public static $Hyponym = "hyponym";
    public static $Inflected_form = "inflected-form";
    public static $Primary = "primary";
    public static $Same_context = "same-context";
    public static $Verb_form = "verb-form";
    public static $Verb_stem = "verb-stem";
    public static $Unknown = "unknown";

};
?>