<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class WordsSearchInput {

  static $swaggerTypes = array(    
    'query' => 'string',
    'caseSensitive' => 'string',
    'includePartOfSpeech' => 'string',
    'excludePartOfSpeech' => 'string',
    'minCorpusCount' => 'string',
    'maxCorpusCount' => 'string',
    'minDictionaryCount' => 'string',
    'maxDictionaryCount' => 'string',
    'minLength' => 'string',
    'maxLength' => 'string',
    'skip' => 'string',
    'limit' => 'string'   
    );


    /**
     * Search term
     */
	 public $query;// string


    /**
     * Search case sensitive
     */
	 public $caseSensitive;// string


    /**
     * Only include these comma-delimited parts of speech
     */
	 public $includePartOfSpeech;// string


    /**
     * Exclude these comma-delimited parts of speech
     */
	 public $excludePartOfSpeech;// string


    /**
     * Minimum corpus frequency for terms
     */
	 public $minCorpusCount;// string


    /**
     * Maximum corpus frequency for terms
     */
	 public $maxCorpusCount;// string


    /**
     * Minimum number of dictionary entries for words returned
     */
	 public $minDictionaryCount;// string


    /**
     * Maximum dictionary definition count
     */
	 public $maxDictionaryCount;// string


    /**
     * Minimum word length
     */
	 public $minLength;// string


    /**
     * Maximum word length
     */
	 public $maxLength;// string


    /**
     * Results to skip
     */
	 public $skip;// string


    /**
     * Maximum number of results to return
     */
	 public $limit;// string


}

?>