<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class WordExamplesInput {

  static $swaggerTypes = array(    
    'word' => 'string',
    'includeDuplicates' => 'string',
    'contentProvider' => 'string',
    'useCanonical' => 'string',
    'skip' => 'string',
    'limit' => 'string'   
    );


    /**
     * Word to return examples for
     */
	 public $word;// string


    /**
     * Show duplicate examples from different sources
     */
	 public $includeDuplicates;// string


    /**
     * Return results from a specific ContentProvider
     */
	 public $contentProvider;// string


    /**
     * If true will try to return the correct word root ('cats' -> 'cat'). If false returns exactly what was requested.
     */
	 public $useCanonical;// string


    /**
     * Results to skip
     */
	 public $skip;// string


    /**
     * Maximum number of results to return
     */
	 public $limit;// string


}

?>