<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class WordListWordsInput {

  static $swaggerTypes = array(    
    'wordListId' => 'string',
    'sortBy' => 'string',
    'sortOrder' => 'string',
    'skip' => 'string',
    'limit' => 'string',
    'auth_token' => 'string'   
    );


    /**
     * ID of WordList to use
     */
	 public $wordListId;// string


    /**
     * Field to sort by
     */
	 public $sortBy;// string


    /**
     * Direction to sort
     */
	 public $sortOrder;// string


    /**
     * Results to skip
     */
	 public $skip;// string


    /**
     * Maximum number of results to return
     */
	 public $limit;// string


    /**
     * The auth token of the logged-in user, obtained by calling /account.{format}/authenticate/{username} (described above)
     */
	 public $auth_token;// string


}

?>