<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class WordsRandomWordsInput {

  static $swaggerTypes = array(    
    'hasDictionaryDef' => 'string',
    'includePartOfSpeech' => 'string',
    'excludePartOfSpeech' => 'string',
    'minCorpusCount' => 'string',
    'maxCorpusCount' => 'string',
    'minDictionaryCount' => 'string',
    'maxDictionaryCount' => 'string',
    'minLength' => 'string',
    'maxLength' => 'string',
    'sortBy' => 'string',
    'sortOrder' => 'string',
    'limit' => 'string'   
    );


    /**
     * Only return words with dictionary definitions
     */
	 public $hasDictionaryDef;// string


    /**
     * CSV part-of-speech values to include
     */
	 public $includePartOfSpeech;// string


    /**
     * CSV part-of-speech values to exclude
     */
	 public $excludePartOfSpeech;// string


    /**
     * Minimum corpus frequency for terms (integer)
     */
	 public $minCorpusCount;// string


    /**
     * Maximum corpus frequency for terms (integer)
     */
	 public $maxCorpusCount;// string


    /**
     * Minimum dictionary count (integer)
     */
	 public $minDictionaryCount;// string


    /**
     * Maximum dictionary count (integer)
     */
	 public $maxDictionaryCount;// string


    /**
     * Minimum word length (characters)
     */
	 public $minLength;// string


    /**
     * Maximum word length (characters)
     */
	 public $maxLength;// string


    /**
     * Attribute to sort by
     */
	 public $sortBy;// string


    /**
     * Sort direction
     */
	 public $sortOrder;// string


    /**
     * Maximum number of results to return
     */
	 public $limit;// string


}

?>